import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import io from 'socket.io-client';

const socket = io('http://localhost:4000');

export default function Home() {
  const [message, setMessage] = useState('');
  const [list, setList] = useState([]);

  const onChangeMessage = (e) => {
    setMessage(e.target.value);
  };

  const sendMessageServer = () => {
    // サーバー送信
    socket.emit('send_message', { message: message });
    setMessage('');
  };

  // サーバー受信
  socket.on('received_message', (data) => {
    // push()
    setList([...list, data]);
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h2>Chat App</h2>
        <div className={styles.chatInputButton}>
          <input onChange={onChangeMessage} value={message} type="text" placeholder="..." />
          <button onClick={sendMessageServer}>Send</button>
        </div>
        {list.map((msg, index) => (
          <div className={styles.chatArea} key={index}>
            {msg.message}
          </div>
        ))}
      </div>
    </div>
  );
}
